services:
  simple-api:
    build:
      context: .
    ports:
      - 5000:80
    networks:
      - my-network
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@ssword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - my-network
    volumes:
      - C:\sql docker:/var/opt/mssql/data
networks:
  my-network:
    driver: bridge